apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: real-estate-storage-pvc
  namespace: real-estate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
