apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: real-estate-dev

resources:
  - ../..

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: real-estate-app
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: real-estate-horizon

configMapGenerator:
  - name: real-estate-config
    behavior: merge
    literals:
      - APP_ENV=development
      - APP_DEBUG=true
      - LOG_LEVEL=debug
      - MODULES_DEVELOPMENT=true
      - MODULES_CACHE=false

images:
  - name: liberu/real-estate
    newTag: develop
